name: Deploy React App to GoDaddy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust the Node.js version if needed

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Build React App
        run: |
          echo "Building React app..."
          npm run build

      - name: List Build Directory
        run: |
          echo "Listing build directory:"
          ls -la build/

      - name: Compress Build Folder
        run: |
          echo "Compressing build folder..."
          zip -r build.zip build/
          echo "Zip file created successfully!"

      - name: Verify Zip File
        run: |
          echo "Verifying the zip file:"
          ls -lh build.zip

      - name: Deploy to GoDaddy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GODADDY_HOST }}
          username: ${{ secrets.GODADDY_USERNAME }}
          key: ${{ secrets.GODADDY_PRIVATE_KEY }}
          port: 22
          source: "build.zip"
          target: "/home/${{ secrets.GODADDY_USERNAME }}/public_html"

      - name: Extract and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GODADDY_HOST }}
          username: ${{ secrets.GODADDY_USERNAME }}
          key: ${{ secrets.GODADDY_PRIVATE_KEY }}
          port: 22
          script: |
            export TERM=xterm  # ✅ Fix: Set TERM variable
            cd /home/${{ secrets.GODADDY_USERNAME }}/public_html
            rm -rf *
            unzip build.zip
            rm build.zip
