name: Deploy React App to GoDaddy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Build React App
        run: |
          echo "Building React app..."
          npm run build

      - name: List Build Directory
        run: |
          echo "Listing build directory:"
          ls -la build/

      - name: Compress Build Folder
        run: |
          echo "Compressing build folder..."
          zip -r build.zip build/
          echo "Zip file created successfully!"

      - name: Verify Zip File
        run: |
          echo "Verifying the zip file:"
          ls -lh build.zip

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GODADDY_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GODADDY_HOST }} >> ~/.ssh/known_hosts
          echo "SSH Key setup complete."

      - name: Test SSH Connection (Debugging Step)
        run: |
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.GODADDY_USER }}@${{ secrets.GODADDY_HOST }} "echo SSH Connected Successfully!"

      - name: Deploy to GoDaddy via SCP
        run: |
          echo "Deploying to GoDaddy..."
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no build.zip ${{ secrets.GODADDY_USER }}@${{ secrets.GODADDY_HOST }}:/home/${{ secrets.GODADDY_USER }}/public_html
